routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    session(['key' => 'value']);
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/google', 'Auth\LoginController@redirectToProvider');
Route::get('/googleCallback', 'Auth\LoginController@handleProviderCallback');

// profile routes
Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', 'ProfileController@index')->name('profile.index');
    Route::get('profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::post('profile/update', 'ProfileController@update')->name('profile.update');

    Route::resource('serviceRooms', 'RoomController');
    Route::post('userServiceRooms/{userServiceRoom}/role/add', 'UserServiceRoomsController@addRole')
        ->name('userServiceRooms.roles.add');
    Route::post('userServiceRooms/{userServiceRoom}/role/{role}/remove', 'UserServiceRoomsController@removeRole')
        ->name('userServiceRooms.roles.remove');
    Route::resource('userServiceRooms', 'UserServiceRoomsController');
    Route::resource('roles', 'RoleController');

});


//Route::resource('profile', 'ProfileController');

app/ServiceRoom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * @property int $id
 * @property int $service_id
 * @property string $name
 * @property int $owner
 * @property Service $service
 * @property Invite[] $invites
 * @property RoomParameter[] $roomParameters
 * @property UserServiceRoom[] $userServiceRooms
 */
class ServiceRoom extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'service_room';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = true;

    /**
     * @var array
     */
    protected $guarded = [];
    public $timestamps = false;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function service()
    {
        return $this->belongsTo('App\Service');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function invites()
    {
        return $this->hasMany('App\Invite');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function roomParameters()
    {
        return $this->hasMany('App\RoomParameter');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function userServiceRooms()
    {
        return $this->hasMany('App\UserServiceRoom');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

resources/views/serviceRooms/create.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{route('serviceRooms.store')}}" method="post">
        @csrf
        <label>
            <select name="service_id" id="" required>Выберите сервис
                <option value="" disabled selected>Выберите сервис</option>
                @foreach($services as $service)
                    <option value="{{$service->id}}">{{$service->name}}</option>
                @endforeach
            </select>
        </label>
        <label for="">
            <input name="name" type="text" required>
        </label>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <button>Добавить комнату</button>
    </form>

    @isset($message)
        <div class="alert alert-success">
           <span>{{$message}}</span>
        </div>
    @endisset
@endsection

resources/views/serviceRooms/index.blade.php
@extends('layouts.app')

@section('content')
    <div>

        @foreach($serviceRooms as $room)
            <div>
                <span>Сервис:{{$room->service->name}}</span>
                <h4>Название: <a href="{{route('serviceRooms.show', $room)}}">{{$room->name}}</a></h4>
            </div>
        @endforeach
    </div>
@endsection

resources/views/serviceRooms/show.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <div>
            <span>Сервис:{{$serviceRoom->service->name}}</span>
            <h4>Название: <a href="{{route('serviceRooms.show', $serviceRoom)}}">{{$serviceRoom->name}}</a></h4>
        </div>
        <div>
            <h2>Список пользователей:</h2>
            <div class="">
                @if($serviceRoom->userServiceRooms->count())
                @foreach($serviceRoom->userServiceRooms as $usr)
                    @if($usr->user_id == auth()->user()->id)
                        @continue
                        @endif
                    <div>
                        <h3>{{$usr->user->id .'--'.$usr->user->email}}</h3>
                    </div>
                    <div>
                        <h5>Роли пользователя:</h5>
                        @foreach($usr->roles as $role)
                            <form action="{{route('userServiceRooms.roles.remove', [$usr->id, $role->id])}}" method="post">
                                @csrf
                                <div>{{$role->name}}</div>
                                <button>Удалить &times;</button>
                            </form>
                        @endforeach
                    </div>
                    <div>
                        <h5>Добавить роль</h5>

                        <form action="{{route('userServiceRooms.roles.add', [$usr->id])}}" method="post">
                            @csrf
                            <select name="role_id" id="">
                                @foreach($roles as $role)
                                    @php
                                        $flag = true;
                                    @endphp
                                    @foreach($usr->roles as $role2)
                                        @if($role2->id == $role->id || $role->name == 'user')
                                            @php
                                                $flag = false;
                                            @endphp
                                        @endif
                                    @endforeach
                                    @if($flag)
                                        <option value="{{$role->id}}">{{$role->name}}</option>
                                    @endif
                                @endforeach
                            </select>
                            <button>Добавить роль пользователю</button>
                        </form>
                    </div>
                @endforeach
                @else
                <strong>Пользователи ещё не были добавлены</strong>
                @endif
            </div>
        </div>
        <h2>Добавить пользователя</h2>
        <form action="{{route('userServiceRooms.store')}}" method="post">
            @csrf
            <input class="input-group" type="hidden" required value="{{$serviceRoom->id}}" name="service_room_id" >

            <div>Id пользователя
                <label for="">
                    <input required pattern="[0-9]+" name="user_id" type="number">
                </label>
            </div>
            <button>Добавить пользователя</button>
        </form>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if(session()->has('message'))
            <div class="alert alert-success">
                <span>{{session('message')}}</span>
            </div>
        @endisset
    </div>
@endsection